CREATE TABLE [Received](
	[ID] UNIQUEIDENTIFIER PRIMARY KEY,
	[SheetID] UNIQUEIDENTIFIER NOT NULL,
	[Money] DECIMAL(18,2) NOT NULL,
	[Time] DATETIME NOT NULL,
	[CreateTime] DATETIME NOT NULL,
	[LastModifyTime] DATETIME NULL,
	[LastModifyUser] UNIQUEIDENTIFIER NULL,
	[Deleted] BIT NOT NULL DEFAULT(0)
)