CREATE TABLE [ReceivedDetail](
	[ID] UNIQUEIDENTIFIER PRIMARY KEY,
	[SheetID] UNIQUEIDENTIFIER NOT NULL,
	[Money] DECIMAL NOT NULL,
	[Time] DATETIME NOT NULL,
	[CreateTime] DATETIME NOT NULL,
	[LastModifyTime] DATETIME NULL,
	[LastModifyUser] UNIQUEIDENTIFIER NULL,
	[Deleted] BIT NOT NULL DEFAULT(0)
)