CREATE TABLE [SheetLog](
	[ID] UNIQUEIDENTIFIER PRIMARY KEY,
	[SheetID] UNIQUEIDENTIFIER NOT NULL,
	[OperatorID] UNIQUEIDENTIFIER NOT NULL,
	[Text] NVARCHAR(500) NOT NULL,
	[CreateTime] DATETIME NOT NULL,
	[Deleted] BIT NOT NULL DEFAULT(0)
)