CREATE TABLE [Sheet](
	ID UNIQUEIDENTIFIER PRIMARY KEY,
	Name NVARCHAR(100) NOT NULL,
	Contacts NVARCHAR(20) NOT NULL,
	Phone VARCHAR(20) NOT NULL,
	QQ VARCHAR(20) NULL,
	WeiXin VARCHAR(30) NULL,
	[Address] NVARCHAR(200) NULL,
	[TimeFrom] DATETIME NOT NULL,
	[TimeTo] DATETIME NOT NULL,
	[Base] UNIQUEIDENTIFIER NOT NULL,
	[People] INT NOT NULL,
	[Source] UNIQUEIDENTIFIER NOT NULL,
)