CREATE TABLE dbo.[User](
	ID UNIQUEIDENTIFIER PRIMARY KEY,
	[Name] NVARCHAR(50) NOT NULL,
	[Password] CHAR(32) NOT NULL,
	[Enabled] BIT NOT NULL DEFAULT(0),
	[LastModifyTime] DATETIME NULL,  
	[LastModifyUser] UNIQUEIDENTIFIER NULL,
	[Deleted] BIT NOT NULL DEFAULT(0)
)