//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SettlementApi.Api.Resource {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CommonRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonRes() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SettlementApi.Api.Resource.CommonRes", typeof(CommonRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Api application error. 的本地化字符串。
        /// </summary>
        internal static string ApiApplicationError {
            get {
                return ResourceManager.GetString("ApiApplicationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证码不正确. 的本地化字符串。
        /// </summary>
        internal static string CaptchaError {
            get {
                return ResourceManager.GetString("CaptchaError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create successful. 的本地化字符串。
        /// </summary>
        internal static string CreateSuccessful {
            get {
                return ResourceManager.GetString("CreateSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete Successful. 的本地化字符串。
        /// </summary>
        internal static string DeleteSuccessful {
            get {
                return ResourceManager.GetString("DeleteSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid session. 的本地化字符串。
        /// </summary>
        internal static string InvalidSession {
            get {
                return ResourceManager.GetString("InvalidSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Modify successful. 的本地化字符串。
        /// </summary>
        internal static string ModifySuccessful {
            get {
                return ResourceManager.GetString("ModifySuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请登录后再进行此操作. 的本地化字符串。
        /// </summary>
        internal static string NotAuthorized {
            get {
                return ResourceManager.GetString("NotAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 会话已经过期，请重新登录. 的本地化字符串。
        /// </summary>
        internal static string SessionExpired {
            get {
                return ResourceManager.GetString("SessionExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Session is not expired. 的本地化字符串。
        /// </summary>
        internal static string SessionNotExpired {
            get {
                return ResourceManager.GetString("SessionNotExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sign out successful. 的本地化字符串。
        /// </summary>
        internal static string SignOutSuccessful {
            get {
                return ResourceManager.GetString("SignOutSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 短信验证码不正确. 的本地化字符串。
        /// </summary>
        internal static string SMSCaptchaError {
            get {
                return ResourceManager.GetString("SMSCaptchaError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 短信验证码已发送，请不要重复发送. 的本地化字符串。
        /// </summary>
        internal static string SMSSend {
            get {
                return ResourceManager.GetString("SMSSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Success 的本地化字符串。
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Upload content type incorrect. 的本地化字符串。
        /// </summary>
        internal static string UploadContentTypeError {
            get {
                return ResourceManager.GetString("UploadContentTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Upload file can not be empty. 的本地化字符串。
        /// </summary>
        internal static string UploadFileEmpty {
            get {
                return ResourceManager.GetString("UploadFileEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Upload the file extension is not allowed extension. 的本地化字符串。
        /// </summary>
        internal static string UploadFileExtensionNotAllowed {
            get {
                return ResourceManager.GetString("UploadFileExtensionNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Upload file size exceeds the limit. 的本地化字符串。
        /// </summary>
        internal static string UploadFileSizeLimit {
            get {
                return ResourceManager.GetString("UploadFileSizeLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上传的图片格式不正确. 的本地化字符串。
        /// </summary>
        internal static string UploadImageTypeError {
            get {
                return ResourceManager.GetString("UploadImageTypeError", resourceCulture);
            }
        }
    }
}
