import { createActions } from 'redux-actions';

export const GET_SHEET = 'GET_SHEET';
export const REQUEST_GET_SHEET = 'REQUEST_GET_SHEET';
export const SUCCESS_GET_SHEET = 'SUCCESS_GET_SHEET';
export const FAILURE_GET_SHEET = 'FAILURE_GET_SHEET';

export const QUERY_SHEETS = 'QUERY_SHEETS';
export const REQUEST_QUERY_SHEETS = 'REQUEST_QUERY_SHEETS';
export const SUCCESS_QUERY_SHEETS = 'SUCCESS_QUERY_SHEETS';
export const FAILURE_QUERY_SHEETS = 'FAILURE_QUERY_SHEETS';

export const CREATE_SHEET = 'CREATE_SHEET';
export const REQUEST_CREATE_SHEET = 'REQUEST_CREATE_SHEET';
export const SUCCESS_CREATE_SHEET = 'SUCCESS_CREATE_SHEET';
export const FAILURE_CREATE_SHEET = 'FAILURE_CREATE_SHEET';

export const UPDATE_SHEET = 'UPDATE_SHEET';
export const REQUEST_UPDATE_SHEET = 'REQUEST_UPDATE_SHEET';
export const SUCCESS_UPDATE_SHEET = 'SUCCESS_UPDATE_SHEET';
export const FAILURE_UPDATE_SHEET = 'FAILURE_UPDATE_SHEET';

export default createActions(
	GET_SHEET,
	REQUEST_GET_SHEET,
	SUCCESS_GET_SHEET,
	FAILURE_GET_SHEET,
	QUERY_SHEETS,
	REQUEST_QUERY_SHEETS,
	SUCCESS_QUERY_SHEETS,
	FAILURE_QUERY_SHEETS,
	CREATE_SHEET,
	REQUEST_CREATE_SHEET,
	SUCCESS_CREATE_SHEET,
	FAILURE_CREATE_SHEET,
	UPDATE_SHEET,
	REQUEST_UPDATE_SHEET,
	SUCCESS_UPDATE_SHEET,
	FAILURE_UPDATE_SHEET
);