import { createActions } from 'redux-actions';

export const QUERY_USERS = 'QUERY_USERS';
export const REQUEST_QUERY_USERS = 'REQUEST_QUERY_USERS';
export const SUCCESS_QUERY_USERS = 'SUCCESS_QUERY_USERS';
export const FAILURE_QUERY_USERS = 'FAILURE_QUERY_USERS';

export const CREATE_USER = 'CREATE_USER';
export const REQUEST_CREATE_USER = 'REQUEST_CREATE_USER';
export const SUCCESS_CREATE_USER = 'SUCCESS_CREATE_USER';
export const FAILURE_CREATE_USER = 'FAILURE_CREATE_USER';

export const UPDATE_USER = 'UPDATE_USER';
export const REQUEST_UPDATE_USER = 'REQUEST_UPDATE_USER';
export const SUCCESS_UPDATE_USER = 'SUCCESS_UPDATE_USER';
export const FAILURE_UPDATE_USER = 'FAILURE_UPDATE_USER';

export const UPDATE_USER_PWD = 'UPDATE_USER_PWD';
export const REQUEST_UPDATE_USER_PWD = 'REQUEST_UPDATE_USER_PWD';
export const SUCCESS_UPDATE_USER_PWD = 'SUCCESS_UPDATE_USER_PWD';
export const FAILURE_UPDATE_USER_PWD = 'FAILURE_UPDATE_USER_PWD';

export default createActions(
	QUERY_USERS,
	REQUEST_QUERY_USERS,
	SUCCESS_QUERY_USERS,
	FAILURE_QUERY_USERS,
	CREATE_USER,
	REQUEST_CREATE_USER,
	SUCCESS_CREATE_USER,
	FAILURE_CREATE_USER,
	UPDATE_USER,
	REQUEST_UPDATE_USER,
	SUCCESS_UPDATE_USER,
	FAILURE_UPDATE_USER,
	UPDATE_USER_PWD,
	REQUEST_UPDATE_USER_PWD,
	SUCCESS_UPDATE_USER_PWD,
	FAILURE_UPDATE_USER_PWD
);
// export const updateUserPwd=()=>action(UPDATE_USER_PWD)